version: '3.8'

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - ENABLE_CELERY=${ENABLE_CELERY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi_app

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:alpine

  # celery_worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: celery -A app.celery_app.celery_app worker --loglevel=info
  #   depends_on:
  #     - redis
  #   environment:
  #     - CELERY_BROKER_URL=${CELERY_BROKER_URL}
  #     - ENABLE_CELERY=${ENABLE_CELERY}

volumes:
  postgres_data:
